environment: local
type: nonprod
packages:
  - name: external-secrets
    enabled: true
    namespace: external-secrets
    category: security
    manifestPath: "security/external-secrets/manifests"
    isChart: false
  - name: cert-manager
    enabled: true
    namespace: cert-manager
    category: security
    manifestPath: "security/cert-manager/manifests"
    isChart: false
  - name: cnpg
    enabled: true
    namespace: cnpg-system
    category: data
    manifestPath: "data/cnpg/manifests"
    isChart: false
  - name: kyverno
    enabled: true
    namespace: kyverno
    category: security
    manifestPath: "security/kyverno/manifests"
    isChart: false
  - name: kyverno-policies
    enabled: true
    namespace: kyverno
    category: security
    manifestPath: "security/kyverno-policies/manifests"
    isChart: false
  - name: jupyterhub
    enabled: true
    namespace: jupyterhub
    category: data
    manifestPath: "data/jupyterhub/manifests"
    isChart: false
  - name: headlamp
    enabled: true
    namespace: adhar-system
    category: observability
    manifestPath: "observability/headlamp/manifests"
    isChart: false
  - name: keycloak
    enabled: true
    namespace: keycloak
    category: security
    manifestPath: "security/keycloak/manifests"
    isChart: false
  - name: argo-workflows
    enabled: true
    namespace: argo
    category: application
    manifestPath: "application/argo-workflows/manifests/dev"
    isChart: false
  - name: adhar-console
    enabled: true
    namespace: backstage
    category: core
    manifestPath: "core/adhar-console/manifests"
    isChart: false
  - name: harbor
    enabled: true
    namespace: harbor
    category: application
    manifestPath: "application/harbor/manifests"
    isChart: false
  - name: kargo
    enabled: true
    namespace: argocd
    category: application
    manifestPath: "application/kargo/manifests"
    isChart: false
  - name: minio
    enabled: true
    namespace: minio
    category: data
    manifestPath: "data/minio/manifests"
    isChart: false
  - name: velero
    enabled: true
    namespace: velero
    category: core
    manifestPath: "core/velero/manifests"
    isChart: false
  - name: spark-operator
    enabled: true
    namespace: spark-operator
    category: data
    manifestPath: "data/spark-operator/manifests"
    isChart: false
  - name: metrics-server
    enabled: true
    namespace: kube-system
    category: observability
    manifestPath: "observability/metrics-server/manifests"
    isChart: false
  - name: kube-prometheus
    enabled: true
    namespace: monitoring
    category: observability
    manifestPath: "observability/kube-prometheus/manifests"
    isChart: false
  - name: loki
    enabled: true
    namespace: monitoring
    category: observability
    manifestPath: "observability/loki-stack/manifests"
    isChart: false
  - name: opencost
    enabled: true
    namespace: monitoring
    category: observability
    manifestPath: "observability/opencost/manifests"
    isChart: false
  - name: alloy
    enabled: true
    namespace: monitoring
    category: observability
    manifestPath: "observability/alloy/manifests"
    isChart: false
  - name: oncall
    enabled: true
    namespace: monitoring
    category: observability
    manifestPath: "observability/oncall/manifests"
    isChart: false
  - name: tempo
    enabled: true
    namespace: monitoring
    category: observability
    manifestPath: "observability/tempo/manifests"
    isChart: false
  - name: mimir
    enabled: true
    namespace: monitoring
    category: observability
    manifestPath: "observability/mimir/manifests"
    isChart: false
  - name: k6
    enabled: true
    namespace: adhar-system
    category: application
    manifestPath: "application/k6/manifests"
    isChart: false
  - name: crossplane
    enabled: true
    namespace: crossplane-system
    category: infrastructure
    manifestPath: "infrastructure/crossplane/manifests"
    isChart: false
  - name: terraform
    enabled: true
    namespace: adhar-system
    category: infrastructure
    manifestPath: "infrastructure/terraform/manifests"
    isChart: false
  - name: dapr
    enabled: true
    namespace: dapr-system
    category: application
    manifestPath: "application/dapr/manifests"
    isChart: false
  - name: redis
    enabled: true
    namespace: redis-operator
    category: data
    manifestPath: "data/redis/manifests"
    isChart: false
  - name: keda
    enabled: true
    namespace: keda
    category: application
    manifestPath: "application/keda/manifests"
    isChart: false
